version: "3"

services:
  server:
    build:
      context: .
    environment:
      PORT: 3000
      NODE_ENV: production
      MONGO_URI: mongodb+srv://<your_mongo_uri>
      JWT_SECRET: <your_jwt_secret>
      EMAIL_USER: <your_email_user>
      EMAIL_PASS: <your_email_pass>
    expose:
      - "3000" # Nur für den internen Docker-Verkehr sichtbar
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Deine Nginx-Konfigurationsdatei
    ports:
      - "80:80" # Leitet Port 80 des Hosts auf den Nginx-Container weiter
    depends_on:
      - server
    networks:
      - backend

networks:
  backend:
    driver: bridge
