services:
  server:
    build:
      context: .
    environment:
      PORT: 3000
      NODE_ENV: production
      MONGO_URI: mongodb://localhost:27017/auth-db
      JWT_SECRET: yourSecretKey
      EMAIL_USER: yourEmail@example.com
      EMAIL_PASS: yourPassword
    ports:
      - 3000:3000
