version: "3"

services:
  server:
    build:
      context: .
    environment:
      PORT: 3000
      NODE_ENV: production
      MONGO_URI: mongodb+srv://<your_mongo_uri>
      JWT_SECRET: <your_jwt_secret>
      EMAIL_USER: <your_email_user>
      EMAIL_PASS: <your_email_pass>
      COOKIE_DOMAIN: <your_domain>
      SESSION_SECRET: <your_session_secret>
    expose:
      - "3000"
    networks:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - server
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
